version: '3.7'
services:
   db:
      container_name: mongodb
      image: mongo
      command: mongod --port 27018
      ports:
         - "27018:27018"
      hostname: mongodb
   api:
      build: .
      ports:
         - "8080:8080"
      depends_on:
         - db